---
extends: vizzuality
env:
  node: true
  es6: true
  browser: true
globals:
  require: true
  config: true
  __DEV__: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
plugins: [react]

rules:
  max-len: [1, 140, 2, {"ignoreUrls":true}]
  comma-dangle: [error, never]
  no-console: [error, allow: [warn, error, info]]
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  arrow-parens: 1
  no-undef: "off"
  import/extensions: [error, {"js": never, "jsx": never}]
  import/no-unresolved: 0
  import/no-extraneous-dependencies: 0
  no-use-before-define: 0
  no-underscore-dangle: 0
  react/forbid-prop-types: 0
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx

      moduleDirectory:
        - node_modules
        - javascript
        - javascript/app
        - app/javascript/app
