---
extends: [
   prettier,
   vizzuality
]
env:
  node: true
  es6: true
  browser: true
  jest: true
globals:
  require: true
  config: true
  __DEV__: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  sourceType: module
plugins: [react, prettier]

rules:
  max-len: [1, 140, 2, {"ignoreUrls":true}]
  comma-dangle: [error, never]
  no-console: [error, allow: [warn, error, info]]
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  arrow-parens: 0
  import/extensions: [error, {"js": never, "jsx": never}]
  import/no-unresolved: 0
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  no-use-before-define: 0
  no-underscore-dangle: 0
  react/forbid-prop-types: 0
  react/prefer-stateless-function: 0
  jsx-a11y/href-no-hash: 0
  jsx-a11y/alt-text: 0
  react/jsx-filename-extension: 0
  camelcase: 0
  prefer-arrow-callback: 0
  func-names: 0
  react/jsx-indent: 1
  no-mixed-operators: 1
  no-confusing-arrow: ["error", { "allowParens": false }]
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx

      moduleDirectory:
        - node_modules
        - javascript
        - javascript/app
        - app/javascript/app
