title: "Climate Watch documentation"
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
# url: "https://vizzuality.github.io/climate-watch/" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: light
# Aux links for the upper right navigation
aux_links:
  "Production site":
    - "https://www.climatewatchdata.org"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Vizzuality/climate-watch" # the github URL for your repo
gh_edit_branch: "develop" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    docs:
      # Give the collection a name
      name: Documentation
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false