FROM ruby:2.5.1
MAINTAINER Jose Angel Parreño <joseangel.parreno@vizzuality.com>

ENV NAME climate-watch
ENV RAKE_ENV development
ENV RAILS_ENV development
ENV CW_API /api/v1
ENV ESP_API https://data.emissionspathways.org/api/v1
ENV S3_BUCKET_NAME climate-watch-dev
ENV GOOGLE_ANALYTICS_ID UA-1981881-51
ENV USER_REPORT_KEY 5fe46fa7-c7e6-40e6-8e48-37479c4599f1

# Install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs build-essential patch zlib1g-dev liblzma-dev libicu-dev \
    && npm install -g yarn

RUN gem install bundler --no-ri --no-rdoc

# Create app directory
RUN mkdir -p /usr/src/$NAME
WORKDIR /usr/src/$NAME
# VOLUME /usr/src/$NAME

# Install app dependencies
COPY Gemfile Gemfile.lock ./

RUN bundle install

# Bundle app source
ARG secretKey
ENV SECRET_KEY_BASE $secretKey
COPY . ./

EXPOSE 3000

# Start app
CMD npm start
