platforms:
  - name: global_cw_platform
    display_name: Climate Watch Global
    sections:
      - name: adaptation
        importer: ImportAdaptation
        datasets:
          - adaptation
          - adaptation_metadata
      - name: agriculture_metadata
        importer: ImportAgricultureMetadata
        datasets:
          - Legend File 823
      - name: agriculture_contexts
        importer: ImportAgricultureContexts
        datasets:
          - Agr FAOSTAT Inputs Sample Data 823
          - Agr FAOSTAT Macro Indicators Sample Data 823
          - Agr FAOSTAT Water Withdrawal Database 823
          - Agr WBD Sample Data 823
      - name: agriculture_profile
        importer: ImportAgricultureProfile
        datasets:
          - Agr FAOSTAT Production and Trade Sample Data 823
          - Agr OECD_FAO Sample Data 823
          - Agr FAOSTAT Land Use Sample Data 823
      - name: agriculture_emissions
        importer: ImportAgricultureEmissions
        datasets:
          - Agr FAOSTAT Emissions Sample Data 823
          - Legend File 823

      - name: historical_emissions
        importer: ImportHistoricalEmissions
        datasets:
          - CW_HistoricalEmissions_metadata_sources
          - CW_HistoricalEmissions_metadata_sectors
          - CW_HistoricalEmissions_CAIT
          - CW_HistoricalEmissions_PIK
          - CW_HistoricalEmissions_UNFCCC
          - CW_HistoricalEmissions_GCP
      - name: indc
        importer: ImportIndc
        datasets:
          - NDC_data
          - NDC_legend
          - NDC_LTS_data
          - NDC_LTS_data_sectoral
          - NDC_WB_data_sectoral_all
          - NDC_submission
          - NDC_metadata
          - NDC_single_version
          - NDC_documents
      - name: locations
        importer: ImportLocations
        datasets:
          - locations
      - name: locations_members
        importer: ImportLocationMembers
        datasets:
          - locations_groupings
      - name: ndc_texts
        importer: ImportNdcTexts
      - name: quantifications
        importer: ImportQuantifications
        datasets:
          - CW_NDC_quantification_commas
      - name: sdgs
        importer: ImportSdgs
        datasets:
          - sdgs
          - sdg_targets
      - name: ndc_sdgs_targets
        importer: ImportNdcSdgTargets
        datasets:
          - ndc_sdg_targets
      - name: socioeconomics
        importer: ImportSocioeconomics
        datasets:
          - indicators_gdp
          - indicators_gdp_per_capita
          - indicators_population
          - indicators_population_growth
      - name: timeline
        importer: ImportTimeline
        datasets:
          - BR
          - BUR
          - GHG18_A1
          - LTS
          - NAP
          - NC_A1
          - NC_NA1
          - NDC_INDC
          - SA
          - cancun
      - name: wb_extra
        importer: ImportWbExtra
        datasets:
          - population
          - gdp
      - name: wri_metadata
        importer: ImportWriMetadata
        datasets:
          - Acronyms
          - metadata_sources
          - metadata_sources_descriptions
      - name: blog_stories
        importer: ImportStories
