platforms:
  - name: global_cw_platform
    display_name: Climate Watch Global
    sections:
      - name: adaptation
        worker: ImportAdaptationWorker
        datasets:
          - adaptation
          - adaptation_metadata
      - name: historical_emissions
        worker: ImportHistoricalEmissionsWorker
        datasets:
          - CW_HistoricalEmissions_metadata_sectors
          - CW_HistoricalEmissions_CAIT
          - CW_HistoricalEmissions_PIK
          - CW_HistoricalEmissions_UNFCCC
      - name: indc
        worker: ImportIndcWorker
        datasets:
          - NDC_CAIT_data
          - NDC_CAIT_legend
          - NDC_WB_data_wide
          - NDC_WB_data_sectoral
          - NDC_submission
          - NDC_metadata
      - name: locations
        worker: ImportLocationsWorker
        datasets:
          - locations
      - name: locations_members
        worker: ImportLocationMembersWorker
        datasets:
          - locations_groupings
      - name: ndc_texts
        # worker:
        datasets:
          - ndc_texts
      - name: quantifications
        worker: ImportQuantificationsWorker
        datasets:
          - CW_NDC_quantification_commas
      - name: sdgs
        worker: ImportSdgsWorker
        datasets:
          - sdgs
          - sdg_targets
      - name: socioeconomics
        worker: nil
        datasets:
          - indicators_gdp
          - indicators_gdp_per_capita
          - indicators_population
          - indicators_population_growth
      - name: timeline
        worker: ImportTimelineWorker
        datasets:
          - BR
          - BUR
          - GHG18_A1
          - LTS
          - NAP
          - NC_A1
          - NC_NA1
          - NDC_INDC
          - SA
          - cancun
      - name: wb_extra
        worker: ImportWbExtraWorker
        datasets:
          - population
          - gdp
      - name: wri_metadata
        worker: ImportWriMetadataWorker
        datasets:
          - Acronyms
          - metadata_sources
          - metadata_sources_descriptions
  # - name: indonesia_platform
  #   sections:
  #     - name: historical_emissions
  #     - name: timeline
  # - name: india_platform
  #   sections:
  #     - name: historical_emissions
  #     - name: timeline
