# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
shared:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>

development:
  secret_key_base: cfbb10362845f90473a479d7f759c57ec7a491ba4512c1eb8ae7e691cb0133f568e666f8b3ef01d6ccb653e56fea199f404bfa3a0685f1ff7b4f44228cbd3774

test:
  secret_key_base: 914633f3c8afd563669bf7cae57c3a96896e470a1f1be26fa1492b40dcf0d858e1d5fe7d651ec0547f18db2511ee74abb1f462c429a9e34f0dc727a152efd3d8
  s3_bucket_name: 'test'
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
