default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  database: climate-watch-shared_development
  url: <%= ENV['SHARED_POSTGRES_URL'] %>

test:
  <<: *default
  database: climate-watch-shared_test

production:
  <<: *default
  database: climate-watch-shared
  url: <%= ENV['SHARED_POSTGRES_URL'] %>
