verbose: true
logfile: ./log/sidekiq.log
development:
  :concurrency: 2
staging:
  :concurrency: 2
demo:
  :concurrency: 2
sandbox:
  :concurrency: 2
production:
  :concurrency: 2
:queues:
  - database
