apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {name}
  namespace: climate-watch
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {name}
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
