apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: climate-watch
  namespace: climate-watch
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: climate-watch
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
